### ISSUE TITLE
Plugin fails

### ISSUE THREAD

**Issue by youngpvprock** [drtshock/ObsidianDestroyer#10]
Well, i'm trying that chest be indestructible, i have tried with durability on 1000 and now with the new update with destructible in false, but don't seems to work, the chest always break.. I let here some part of materials.yml of chest and some photos.

Config --> http://pastebin.com/ceXbDZjP
Photos:
Before explosion, you can see 3 double chests with lot of tnt --> http://i.imgur.com/Lg2Enmw.png
After explosion --> http://i.imgur.com/cIocepw.png

Help please :s

**Comment by youngpvprock** [comment]
When i check with durability appears this: 
http://i.imgur.com/D5BriRH.png
But like i said, if you put a lot of tnt near then it deatroy the chest.

**Comment by youngpvprock** [comment]
What happend whit that bug? :/
I'm still waiting the update..

**Comment by squidicuzz** [comment]
I still don't understand this issue completely.  It occurs with bedrock as well, and the Y blocking limits.  I am considering rewriting the plugin in an attempt to figure this out and clean up the code.  The additional features tacked in, and the mess that is Factions support may have introduced something.

**Comment by squidicuzz** [comment]
I think I fixed it.

**Comment by squidicuzz** [comment]
Please open a new issue if this is still occurring.  I can no longer duplicate when using large amounts of TNT and an indestructible material.
