### ISSUE TITLE
No TNTCannon protection

### ISSUE THREAD

**Issue by zRiaz** [drtshock/ObsidianDestroyer#11]
Using latest build posted on Spigot, did update it again just to make sure.
Removed the config and let it regenerate. Changed the setting to protect cannons.
Reloaded the plugin but no change. Ive checked my config and it says that its set to protect cannons.

Using:
Factions: FactionsUUID
Spigot: Spigot 1.8 (Latest update)
OD: (Lastest update) aka 4.3.7
Test: You can go to my server and see for yourself. mc.ironraid.co - /server factions and do /wild
Config: 
Explosions:
  BypassAllFluidProtection: true

  # Protects "TNT cannons" from being destroyed when used. 
  # This doesn't do anything unless the above option is true.
  TNTCannonsProtected: true

Blows up everytime.
Got some angry players due to this, so a quick fix is apprechiated <3

**Comment by drtshock** [comment]
Can you paste a list of all your plugins please.

**Comment by zRiaz** [comment]
Ill pm them to you on Spigot instead.

**Comment by drtshock** [comment]
This isn't an issue with OD.

**Comment by zRiaz** [comment]
It was a setting in FactionsUUID, sorry. Got it solved.
