### ISSUE TITLE
FluidDamper does not apply for FluidsProtectIndustructables false

### ISSUE THREAD

**Issue by gh0ztbuster** [drtshock/ObsidianDestroyer#12]
Can you fix it so FluidDamper enables when "FluidsProtectIndustructables: false"? Currently "BypassAllFluidProtection: true" is the only thing that enables the FluidDamper in the materials.yml.

**Comment by gh0ztbuster** [comment]
Bump

**Comment by gh0ztbuster** [comment]
This is urgent now, I will be posting my updates soon and I need this bug/overlook fixed.

This is not an additional feature, I need "FluidsProtectIndustructables: false" to enable FluidDamper in materials.yml. This will allow me to make obsidian nerfed by water and blocks such as fences not nerfed by water. This prevents ungriefable bases while still retaining the "ObsidianDestroyer" concept.

I posted on GitHub like a week ago <- My updates go live in a couple of days

**Comment by squidicuzz** [comment]
Uh, they are two completely unrelated features... FluidsProtectIndustructables was to correct the issue of obsidian taking damage in liquids, when it shouldn't... and BypassAllFluidProtection makes liquids destructible.

To do what you ask would require a different option in the configuration file.  I will look into it and get back to you.

**Comment by gh0ztbuster** [comment]
Hmm, Thanks for the help. To be honest I thought it would be a simple fix to enable the FluidDamper on "FluidsProtectIndustructables: false"

**Comment by justin2001** [comment]
@drtshock I am running a private faction server and I really need your obsidian destroyer plugin to make obsidian and bedrock raidable. I cant afford your plugin but I desperately need it to for raiding with friends in my private server. Please give me a copy of the plugin. Thanks!

**Comment by HunterGPlays** [comment]
"This will allow me to make obsidian nerfed by water and blocks such as fences not nerfed by water."
I also need this ASAP. 
I'm not going to set up every single material in the material.yml, turn on BypassAllFluidProtection, and set the FluidDamper to 1 to all of them apart from obsidian. It's way easier to enable FluidsProtectIndustructables and set FluidDamper to my existing materials.

**Comment by HunterGPlays** [comment]
This is pretty much the same as https://github.com/drtshock/ObsidianDestroyer/issues/23 as OP (and I) wants fences to blow up under water.

**Comment by HunterGPlays** [comment]
@squidicuzz @drtshock Please add this in as soon as possible. This is a premium plugin, it shouldn't take 6 months to add a config option.

**Comment by HunterGPlays** [comment]
@drtshock how much would I have to pay for you to add this in?

**Comment by squidicuzz** [comment]
Working on it..
