### ISSUE TITLE
I am so confused

### ISSUE THREAD

**Issue by YepImRobbie** [drtshock/ObsidianDestroyer#14]
I have no idea how I would make it so cobble is 100% water protected.

What settings do I turn on/off in what configs, just an overall what the hell do I do.

**Comment by gh0ztbuster** [comment]
Make sure cobblestone isn't enabled in your materials.yml and that "FluidsProtectIndustructables: true" and "BypassAllFluidProtection: false" in the config.yml

**Comment by squidicuzz** [comment]
Please open a new issue if this is still a problem.
