### ISSUE TITLE
Indestructible material doesn't work on Spigot 1.8.3

### ISSUE THREAD

**Issue by dartasen** [drtshock/ObsidianDestroyer#16]
Just a bug with Spigot 1.8.3.
Indestructible material blow up with about ten tnt at the same time.

**Comment by drtshock** [comment]
huh

**Comment by dartasen** [comment]
I love this support and bug fix, very very good, you sell a plugin 15$ and you're not able to fix bug.

In Spigot 1.8.3 it's no longer possible to protect a block from explosion. Destructible option doesn't work and event if we set a high amount it blow up with about ten tnt at the same time.

**Comment by drtshock** [comment]
If I understood what you were saying I'd be able to fix it ._. Which destructible option? Can you paste your entire server log, config.yml and materials.yml in pastebin or a gist as well as the output of /version and /version obsidiandestroyer.

**Comment by dartasen** [comment]
Destructible option in materials.yml... It's your plugin, do you know what you put in it?
Neither error or warn in server log.
Config : http://pastebin.com/8hXCfRe1
Materials : http://pastebin.com/5a9V1ubM

[02:19:40 INFO]: This server is running CraftBukkit version git-Spigot-c136710-350cb99 (MC: 1.8.3) (Implementing API version 1.8.3-R0.1-SNAPSHOT)
[02:19:40 INFO]: You are running the latest version

[02:21:02 INFO]: ObsidianDestroyer version 4.3.7
[02:21:02 INFO]: Authors: drtshock and squidicuz

**Comment by dartasen** [comment]
Up...

**Comment by squidicuzz** [comment]
Apologies, I have not had time as of recent to focus on correcting this issue.  I will fix this issue soon.

**Comment by drtshock** [comment]
The folks over at spigot decided to break plugins again without letting anyone know about it.
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/e387d8dc7752a7f03e6baa1dadaf66ec2e7e3512
https://hub.spigotmc.org/jira/browse/SPIGOT-751

We won't be supporting 1.8.3 until it's stable and there aren't breaking commits every fucking day.
