### ISSUE TITLE
Tnt has no effect on obsidian.

### ISSUE THREAD

**Issue by MGNKylan** [drtshock/ObsidianDestroyer#17]
Just got the plugin a few hours ago, I started my server up and then placed down a piece of obsidian and ive dropped atleast 30 pieces of tnt onto it but it hasn't disappeared. Its very important for my factions server that this plugin works. Im using ObsidianDestroyer version 3.4.2 for my minecraft 1.6.4 server. I hope ive given enough information.

**Comment by drtshock** [comment]
Can you paste your entire server log in a gist or pastebin please

**Comment by MGNKylan** [comment]
https://gist.github.com/495b434d84ac947abfe8.git

**Comment by MGNKylan** [comment]
Sorry for the late reply.

**Comment by MGNKylan** [comment]
![2015-03-19_10 48 58](https://cloud.githubusercontent.com/assets/11550648/6734371/6f7407fc-ce1d-11e4-9475-7c25c0118567.png) Btw heres a picture. Couldnt blow it up. Used 3000 tnt.

**Comment by drtshock** [comment]
Try hitting it with a potato. See if the durability shows up.

**Comment by MGNKylan** [comment]
See the potato in my inventory? Nothing showed up when I did.

**Comment by drtshock** [comment]
RIP. Something must've messed up. Thanks for reporting this, will get to it in a few after I finish up something else :)

**Comment by MGNKylan** [comment]
Any progress?

**Comment by drtshock** [comment]
OH. Just disable the auto updater and you're good to go :)

**Comment by MGNKylan** [comment]
Didnt work. Potato still dosent show durability and obsidian still wont blow up.

**Comment by squidicuzz** [comment]
It sounds like the plugin isn't even enabling.

If this is still an issue, please create another ticket, or re-open this one.
