### ISSUE TITLE
About obsidiandestroyer

### ISSUE THREAD

**Issue by Joe26** [drtshock/ObsidianDestroyer#21]
Hi, I saw that drtshock offers a free copy to a non profitable non 24/7 server which is what I am I wanna run a server for fun and to mess around on but I need a plugin that allows tnt and withers to break obby and he gave me a free copy ages ago but I no longer have it I must have deleted it is there anyway you can give me a new free copy I run 1.8.4 if you can that will be great I would be greatly thankful.

**Comment by drtshock** [comment]
What server do you run?

**Comment by Joe26** [comment]
What do you mean sorry I sound stupid asking this Factions I believe is what your asking and if its for the ip its 80.6.20.112

**Comment by Joe26** [comment]
Because your obviously busy and cannot get back to me at the moment my server is now down for a bit due to I am going out so you wont able to access it however if you want to access it tomorrow that is fine :) I am glad your willing to give me a copy of the plugin

**Comment by drtshock** [comment]
What's your server's website?

**Comment by Joe26** [comment]
I do not have one up yet as without this plugin there will be no server However if you are willing to give me it I shall start setting up the website simply the server just has the plugins and a temp spawn for now intill I know that I will able to get the plugin

**Comment by drtshock** [comment]
Are you going to use buycraft or minecraft market?

**Comment by Joe26** [comment]
No I am allowing people to get ranks on my server by buying them with ingame money not donations I hope this clears things up sorry for late reply trying to cook tea lol

**Comment by Joe26** [comment]
I am now sleeping so we need to finish this tomorrow sorry its quite difficult doing this when we different timezones

**Comment by Joe26** [comment]
Hi I'm back you can

**Comment by Joe26** [comment]
Can I have a copy then? or is there more questions

**Comment by Joe26** [comment]
I am a bit concerned weather or not I can get this plugin to open my server

**Comment by drtshock** [comment]
Handling on skype.
