### ISSUE TITLE
bedrock won't destroy in the nether?

### ISSUE THREAD

**Issue by dzzys** [drtshock/ObsidianDestroyer#22]
So i use ObsidianDestoryer as a obsidian and bedrock destroyer and just recently the bedrock in the nether is impossible to break without gamemode. Anyone got any ideas on how to fix this?

**Comment by drtshock** [comment]
Are you breaking it with a potato? That would be the only time that OD does anything with clicking blocks.

**Comment by dzzys** [comment]
No with /tnt /fireball or creeper eggs

**Comment by drtshock** [comment]
What did you set its durability to? And what Y level are you trying to destroy it at?

Paste your materials.yml and config.yml in pastebin please.

**Comment by dzzys** [comment]
Y Level is 128+ ( Above the nether)

config : http://pastebin.com/17HAtzcK
materials : http://pastebin.com/19H8gUPP

**Comment by drtshock** [comment]
``# When bedrock destruction is enabled, this prevents holes into the void and top of the nether.
# HOLY CRAP DON'T TURN THIS OFF
ProtectBedrockBorders: true``

**Comment by drtshock** [comment]
```
# When bedrock destruction is enabled, this prevents holes into the void and top of the nether.
# HOLY CRAP DON'T TURN THIS OFF
ProtectBedrockBorders: true
```

**Comment by dzzys** [comment]
Thanks man xD i feel stupid cause i skipped that. It's working now anyway

**Comment by drtshock** [comment]
;D
