### ISSUE TITLE
Certain materials BypassAllFluidProtection

### ISSUE THREAD

**Issue by DahFrozen** [drtshock/ObsidianDestroyer#23]
Hi, 
It thought it would be a great idea if you could add the option to configure what blocks ignore water protection. For example:

  OBSIDIAN:
    BlastRadius: 2
    BypassAllFluidProtection: true <--- this means that Obsidian takes damage through liquids.
    Durability:
      Amount: 13
      FluidDamper: 0.07
      Enabled: true
      ChanceToDrop: 0.6
      ResetEnabled: true
      ResetAfter: 600000
    EnabledFor:
      TNT: true
      Creepers: false
      Ghasts: false
      Cannons: true
      Withers: false
      Minecarts: false

Thanks,
Frozon

**Comment by squidicuzz** [comment]
Try the latest version.

**Comment by squidicuzz** [comment]
BypassAllFluidProtection: true 

Enabled fluid damage override per material.

Added and working in version 4.4.5
