### ISSUE TITLE
Indestructible material fix ?

### ISSUE THREAD

**Issue by dartasen** [drtshock/ObsidianDestroyer#24]
I had already posted this issue there is quite some time and you replied:
"We won't be supporting 1.8.3 until it's stable and there aren't breaking commits every fucking day."

But now it's been a while that Spigot is stable and it might be time to fix the bug, you don't update your plugin and it remains paying.

--> https://github.com/drtshock/ObsidianDestroyer/issues/16

**Comment by drtshock** [comment]
We've been supporting 1.8.3 for a while. https://github.com/drtshock/ObsidianDestroyer/commit/4cbf3123b5058fae2982a58c09cdc9d93c474222
