### ISSUE TITLE
Wither don't make damage

### ISSUE THREAD

**Issue by dartasen** [drtshock/ObsidianDestroyer#25]
Wither's explosions don't make damage to obsidian even if it is set "true"

**Comment by drtshock** [comment]
Can you paste your config.yml, materials.yml, and entire server log please with debug mode enabled.

**Comment by dartasen** [comment]
config.yml : http://pastebin.com/U6aQVv5i
materials.yml : http://pastebin.com/g0LTmrg6

How to enable debug mode ?

**Comment by drtshock** [comment]
Oh my bad, forgot we don't have a toggle in master for debug mode. 

Can you also paste your server log? And are you sure it's not taking damage? Check with the tripwire hook.

**Comment by dartasen** [comment]
Yes I have check and test in many way and with others materials like enchanting table, enderchest...

In my server log, there is absolutely nothing about this problem...

When the server start :
[13:37:50 INFO]: [ObsidianDestroyer] Loading ObsidianDestroyer v4.3.7
[13:38:02 INFO]: [ObsidianDestroyer] Enabling ObsidianDestroyer v4.3.7
[13:38:02 INFO]: [ObsidianDestroyer] Loading config File...

And 0 message when a wither explode.
http://prntscr.com/7gswwj

PS : Can you add me on dev build (same name : Dartasen)

**Comment by dartasen** [comment]
Up ?

**Comment by drtshock** [comment]
When I say the server log, paste the entire log in a log file please.

**Comment by dartasen** [comment]
Ok so : http://pastebin.com/7k1eRWVM
But I'm sure that it will not help you.

And I've posted a new message on Spigot thread : https://www.spigotmc.org/threads/obsidiandestroyer-paid.33791/page-7
Because indestructible materials isn't fix yet... (screen in support)

**Comment by dartasen** [comment]
Up

**Comment by squidicuzz** [comment]
Fixed
