### ISSUE TITLE
BlockExplodeEvent

### ISSUE THREAD

**Issue by Agazed** [drtshock/ObsidianDestroyer#27]
Getting this error when obsidian is exploded next to TNT: http://pastebin.com/AEkUpNAr 

Using 4.3.8 and Spigot 1.8.7

**Comment by drtshock** [comment]
Thanks!

**Comment by AwaaX** [comment]
Is it fixes ? because I have the same problem

**Comment by Agazed** [comment]
Still getting this error. http://pastebin.com/ANJnJgxR

4.3.9 and Spigot 1.8.7

**Comment by drtshock** [comment]
That should take care of it.

**Comment by drtshock** [comment]
rip

**Comment by AwaaX** [comment]
BlockExplodeEvent problem to ObsidianDestroyer 4.3.10
http://pastebin.com/dJLjaADu

**Comment by Agazed** [comment]
Was fixed since b343ea9

Thank you for the fix!

**Comment by AwaaX** [comment]
drtshock can you add in the config the radius do you use when we use the cannons plugin ? And add the huge explosion effect on the tnt ?

**Comment by AwaaX** [comment]
?

**Comment by drtshock** [comment]
One issue per ticket @AwaaX
