### ISSUE TITLE
Cannons plugin can't pass BlockExplodeEvent to OD

### ISSUE THREAD

**Issue by HunterGPlays** [drtshock/ObsidianDestroyer#29]
I am running the latest versions of Cannons and ObsidianDestroyer. The server is running version 1.8.7-R0.1-SNAPSHOT.

https://gist.github.com/HunterGPlays/42d1356031477848342f

**Comment by drtshock** [comment]
Duplicate of https://github.com/drtshock/ObsidianDestroyer/issues/27
