### ISSUE TITLE
1 Hit materials don't take damage in faction land.

### ISSUE THREAD

**Issue by DahFrozen** [drtshock/ObsidianDestroyer#32]
Hi,

I have just recently updated to the latest build of ObsidianDestroyer and I have noticed that materials that have 1 durability do not blow up in claimed faction land (apart from wilderness). Here is my materials.yml http://pastebin.com/Y2rcaQcY.

Thanks,
Frozon.

**Comment by drtshock** [comment]
Which specific material? Which version of Obsidiandestroyer, factions, and spigot?

**Comment by DahFrozen** [comment]
Hi,

I have just been testing again and I've found out that the issue is not related to the specific faction claim land. Materials with one durability such as Endstone do not blow up in this occasion http://prntscr.com/7o04g8 (vertical wall). But, the Endstone does blow up when the the wall is horizontal: http://prntscr.com/7o05j6.

Server version: Paper-Spigot 1.8.7
ObsidianDestroyer version: 4.3.9-SNAPSHOT
Factions version: 2.7.5

Thanks,
Frozon.

**Comment by drtshock** [comment]
Interesting. I'm about to take off for the weekend but I'll assign @squidicuzz to see if he can look at it while I'm out. If not, then I'll take a look when I get back.

**Comment by DahFrozen** [comment]
Okay thanks.

**Comment by DahFrozen** [comment]
Does the new update you have released fix this?

**Comment by DahFrozen** [comment]
Is this fixed in the dev builds? If so, can i have a link to the dev builds? Thanks.

**Comment by DahFrozen** [comment]
When will this be fixed? It's been 20 days. @squidicuzz @drtshock

**Comment by drtshock** [comment]
@squidicuzz is slowly working on a new major version update.

**Comment by squidicuzz** [comment]
So... This is a result of the shape of the "sphere" that is created around the explosion point to handle the blocks.  It is not perfect and there is a noticeable difference on the height axis.  What is the BlastRadius set for the Ender_Stone? Try increasing it some. I may have improved this in the upcoming new version as well.

**Comment by squidicuzz** [comment]
I think I fixed the one hit materials issue as well.

**Comment by squidicuzz** [comment]
Closing. I can't duplicate.  Please create a new ticket if this issue persists.
