### ISSUE TITLE
How would I grab the durability of an item?

### ISSUE THREAD

**Issue by Kozs** [drtshock/ObsidianDestroyer#35]
Is there a way for me to grab the durability of a specific block for my plugin? Durability as in how many more tnt shots it'll take to break

**Comment by drtshock** [comment]
Not a very clean way currently but you can get the ChunkWrapper https://github.com/drtshock/ObsidianDestroyer/blob/master/obsidiandestroyer/src/main/java/com/drtshock/obsidiandestroyer/managers/ChunkManager.java#L1252 and then get the durability of a location in that chunk https://github.com/drtshock/ObsidianDestroyer/blob/master/obsidiandestroyer/src/main/java/com/drtshock/obsidiandestroyer/managers/ChunkWrapper.java#L88
