### ISSUE TITLE
Some chunks don't blow up

### ISSUE THREAD

**Issue by Keytoll** [drtshock/ObsidianDestroyer#37]
Some chunks inside my multiverse world (not sure if this works in main world) won't blow up, sometimes they will get 1 shotted aswell. I'm running paperspigot 1.7.10-1.8 protocol hack.
Here are my files:
http://pastebin.com/sBxRzZX2
http://pastebin.com/RNgvS7Nv

**Comment by Jacksparrow3007** [comment]
Any updates on this? I really need this fixed :(

**Comment by squidicuzz** [comment]
It is on the list of things to do.  Apologies, I have been preoccupied with other activities.

Could you please try setting: DisableDamageBleeding to false?  I have had luck with others and disabling this function.  It seems to no longer work correctly on all version of the server mod.

**Comment by Jacksparrow3007** [comment]
Ok, i'll see if that fixes it, really need this fixed :(

**Comment by Jacksparrow3007** [comment]
That doesn't fix it :(

**Comment by squidicuzz** [comment]
Is this still happening?  Could you try the latest dev build please?
