### ISSUE TITLE
Lag spikes (entity explode event)

### ISSUE THREAD

**Issue by Kira07** [drtshock/ObsidianDestroyer#39]
http://image.noelshack.com/fichiers/2015/40/1443824702-faction.png

This performance issue is really annoying and often cause big lag spikes

**Comment by drtshock** [comment]
You'd have to have a lot of people exploding a lot of things. I mean like, alot
!(alot)[http://4.bp.blogspot.com/_D_Z-D2tzi14/S8TRIo4br3I/AAAAAAAACv4/Zh7_GcMlRKo/s400/ALOT.png]

**Comment by Kira07** [comment]
http://pastebin.com/8EsZ5iHb

Here it is, and no there is no massive amounts of tnt spammed, I made sure of that, the spikes happens on a regular basis

**Comment by Kira07** [comment]
Anything new ? This bug is really killing my performance, you're a good
dev, I hope you'll manage to fix it asap..

2015-10-02 23:35 GMT+01:00 Trent Hensler <notifications@github.com>:

**Comment by Agazed** [comment]
How many explosions do you have going on?

**Comment by Kira07** [comment]
No Idea, I limited the tnt per tick to 10 in spigot.yml so players shouldn't be able to spam explosions, and the lagspikes happens really often

**Comment by squidicuzz** [comment]
Do you have a lot of factions in the nether?

**Comment by Kira07** [comment]
Nah but anyway, the bug came from factions & is fixed now ;)

2015-12-27 13:00 GMT+01:00 squidicuz <notifications@github.com>:

**Comment by squidicuzz** [comment]
Okay, well just in case I improved some of the hooks for factions.  The latest latest build has them.
