### ISSUE TITLE
Many issues

### ISSUE THREAD

**Issue by Elgorond** [drtshock/ObsidianDestroyer#4]
I am having quite a bit of issues with Obsidian Destroyer lately. I am assuming it is because of how I updated to Factions/MCore 2.7.4, then downgraded back to 2.7.3. I did this because I did not realize 2.7.4 is meant for spigot 1.8x only.

The current issues are that blocks that are enabled in the materials.yml with durability set to over 1 won't get destroyed. Also, using the item to check block durability (potato) will not do anything. It won't break the block when clicking (as expected), but it won't display anything in chat.
Error when clicking block with potato: http://pastebin.com/PVEH09kS
Error when trying to tnt blocks: http://pastebin.com/SbuJQZtU

I'm currently using ObsidianDestroyer version 4.3.5 and Factions/MCore 2.7.3 with these issues.  Additionally, Obsidian Destroyer is hooking with Factions 2.6.X even though I'm using 2.7.3, the same issue at https://github.com/drtshock/ObsidianDestroyer/issues/3

[00:00:16] [Server thread/INFO]: [ObsidianDestroyer] Enabling ObsidianDestroyer v4.3.5
[00:00:16] [Server thread/INFO]: [ObsidianDestroyer] Loading config File...
[00:00:16] [Server thread/INFO]: [ObsidianDestroyer] Factions hook for version 2.6.X has been loaded!

**Comment by braystone** [comment]
Im getting the 404 error aswell logged in and sitll get it

**Comment by drtshock** [comment]
There currently aren't dev builds. Everything is on Spigot.
