### ISSUE TITLE
materials.yml material names link dont work

### ISSUE THREAD

**Issue by trickz88** [drtshock/ObsidianDestroyer#42]
Hi, this not a bug or anything like that. This just a link notices that need to be updated in the material.yml. The link at the bottom of the material.yml to get material names dose not work. It just gives 404 error. I have tried it many times on different computer still don't work.

So you know what i'm talking about ill past my config, and past the part where the link is at the bottom.

My config: http://pastebin.com/jV0GzCFx

This is the link i found and works and I was wanting to know if this will work for the config?
https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html

**Comment by drtshock** [comment]
Yeah use that.
