### ISSUE TITLE
What version of bukkit does this work on?

### ISSUE THREAD

**Issue by Trilad** [drtshock/ObsidianDestroyer#43]
I have bukkit 1.8.8 and i added it and customized the materials.yml and config.yml but when i try and do /od reload it just gives me the text of what it says /od<reload:reloadDB:reset:version>. it also will not show me the durability of a block.

**Comment by drtshock** [comment]
Check your logs to see if it enabled correctly. Might just be a case of returning false instead of true in (doesn't make a difference)

**Comment by Trilad** [comment]
@drtshock Here is the console error log, http://pastebin.com/Ry7FHjSt. i dont know what it means.

**Comment by drtshock** [comment]
You have invalid yaml. Put it in a yaml parser to find your problem :)

**Comment by Trilad** [comment]
@drtshock i put it in a yaml parser and it gives me the error but i do not know how to fix it, sorry i am not the greatest at these things, i can setup servers and all that but when it comes to troubleshooting i best come to the professionals.

**Comment by Trilad** [comment]
@drtshock  nevermind i have managed to fix my issue
