### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by Jack07551** [drtshock/ObsidianDestroyer#44]
Dear drtshock,
I've just started up a factions server and have not earned any money because I cant release it until I have the correct plugins. The plugin I need is obsidian destroyer and all the other plugins that destroy obsidian do not work properly and i cant afford to pay for yours so I was wondering if you could help me with what to do.

**Comment by drtshock** [comment]
no

**Comment by Jack07551** [comment]
Thanks for the help..

**Comment by Jack07551** [comment]
so useful

**Comment by drtshock** [comment]
yep!
