### ISSUE TITLE
enhancement: Factions hook, only explode if power is low. 

### ISSUE THREAD

**Issue by Done84** [drtshock/ObsidianDestroyer#46]
It would be awesome if this could hook into factions and have an option to only blow up certain blocks if the faction has the power level below their land level.

**Comment by squidicuzz** [comment]
Try Version 4.4.11-SNAPSHOT

I added config option and an option in material.yml to override the factions power setting.

**Comment by Done84** [comment]
Not sure if I'm doing something wrong but its not really working.

Version 4.4.11_snapshot build #213
Config: http://pastebin.com/zzjjhzvW
Materials: http://pastebin.com/Ge5kXHGM

**Comment by Done84** [comment]
After some more testing... this is my conclusion:
The newly generated Materials.yml does not seem to work, i had to use the older file from the previous version. Also i don't se any 'new option' there.

Only with  factions hook off the obsidian actually breaks and the potato works.
> Factions:
>  Enabled: false

Otherwise it doesn't work.

**Comment by Done84** [comment]
Er... Bump?
