### ISSUE TITLE
bedrock not blowing up

### ISSUE THREAD

**Issue by fatsx** [drtshock/ObsidianDestroyer#47]
Hello, I am using v 4.4.6-snapshot.
obsidian works fine.   Bedrock does not.   I enabled it, but it never gets destroyed.   
I placed bedrock in creative mode and tried to tnt it and it still says 30/30 (changed the amount)

any suggestions?

  OBSIDIAN:
    BlastRadius: 2
    Durability:
      Amount: 6
      FluidDamper: 0.07
      Enabled: true
      ChanceToDrop: 0.6
      ResetEnabled: true
      ResetAfter: 600000
    EnabledFor:
      TNT: true
      Creepers: true
      Ghasts: false
      Cannons: true
      Withers: false
      Minecarts: false
  BEDROCK:
    BlastRadius: 2
    Durability:
      Amount: 30
      Enabled: true
      ChanceToDrop: 0.5
      ResetEnabled: true
      ResetAfter: 1800000
    EnabledFor:
      TNT: true
      Creepers: true
      Ghasts: false
      Cannons: true
      Withers: false
      Minecarts: false

**Comment by squidicuzz** [comment]
Yes, there was a bug.  Try the latest version, it is fixed.
