### ISSUE TITLE
ObsidianDestoryer not working with Factions v1.6.9.4

### ISSUE THREAD

**Issue by TheMasteredPanda** [drtshock/ObsidianDestroyer#48]
Yo,

Says it all in the title, when I put in ObsidianDestoryer not only did it not work, but it made regeneration of hungry regenerate really fast. Am I using the wrong jar for the wrong factions version or?

**Comment by drtshock** [comment]
what o_O are you sure you're using obsidiandestroyer?

**Comment by TheMasteredPanda** [comment]
Yeah I'm using ObsidianDestroyer v3.4.1

**Comment by TheMasteredPanda** [comment]
With Factions v1.6.9.4

**Comment by drtshock** [comment]
I doubt that. Can you paste your startup log in a pastebin please.

**Comment by TheMasteredPanda** [comment]
http://pastebin.com/yLAX9Dhj

**Comment by drtshock** [comment]
You're on a super old version. Update.
