### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by Agazed** [drtshock/ObsidianDestroyer#50]
I'm not sure what caused my server to crash, but I was left with a long error report and I'm not sure how to read it:

http://pastebin.com/T15A1Ciy

Specifically,

`com.drtshock.obsidiandestroyer.managers.ChunkWrapper.save(ChunkWrapper.java:197), com.drtshock.obsidiandestroyer.managers.ChunkManager.save(ChunkManager.java:1264), com.drtshock.obsidiandestroyer.ObsidianDestroyer.onDisable(ObsidianDestroyer.java:167), org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:323),`

**Comment by Agazed** [comment]
bump

**Comment by squidicuzz** [comment]
Old issue..  Not sure if valid.  Create new ticket if still happens please.
