### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by tehrenderr** [drtshock/ObsidianDestroyer#53]
Tested this multiple times with the latest version, enderhchests do not blow up, neither does anvils. I have bypassfluidprotection and destructible set to true with lava and stationary lava and that doesnt blow up either.

**Comment by drtshock** [comment]
which spigot and od versions?

**Comment by tehrenderr** [comment]
Od version 4.4.11
Spigot version: https://gyazo.com/4f0fa2c6fff4ef41eabb0e6017185431

**Comment by tehrenderr** [comment]
So...?

**Comment by Agazed** [comment]
Update to Spigot 1.9

**Comment by tehrenderr** [comment]
Not an option, the plugin should be working for version 1.7/1.8

**Comment by drtshock** [comment]
Can you paste your server startup log in pastebin please.

**Comment by tehrenderr** [comment]
Here is my startup log
http://pastebin.com/TrjUBsrJ
Here is my materials.yml
http://pastebin.com/FRqFdWNW

In the startup log I am using 4.4.5 not 4.4.11 since that doesn't work. 4.4.5 has it's issues too. Enderchests and anvils aren't exploding and stationary and flowing lava isn't being blown up by tnt even though I have bypassfluidprotection set to true and destructible set to true, it only blows up the source block.

**Comment by tehrenderr** [comment]
Were you able to replicate the issue with my materials.yml?

**Comment by tehrenderr** [comment]
tik tok

**Comment by squidicuzz** [comment]
I'll have it fixed by this weekend. Apologies, I haven't had a chunk of time to dig into issues recently.

**Comment by tehrenderr** [comment]
Have you had time to look at it, it's been weeks since I brought this issue up...

**Comment by tehrenderr** [comment]
Hello?....

**Comment by tehrenderr** [comment]
Well the weekend is now over, still no fix. Iv'e messaged you about this issue weeks ago. $15 down the drain.

**Comment by tehrenderr** [comment]
bump

**Comment by drtshock** [comment]
@squidicuzz pls

**Comment by tehrenderr** [comment]
@squidicuzz

**Comment by squidicuzz** [comment]
Sorry.  Not sure if this is still valid.  Please re-open and I will resolve...  `.___.`
