### ISSUE TITLE
Doesn't even work

### ISSUE THREAD

**Issue by miremo** [drtshock/ObsidianDestroyer#54]
I installed obsidian destroyer the latest version and a 1.8 version of spigot and when I type the commands /od I see all the information but it does not effect the blocks when tnt or any explosion hits. And when I hit it with a potato I do not get anything in chat.

**Comment by miremo** [comment]
Nothing in the config is changed at all have not touched it.

**Comment by drtshock** [comment]
Paste your startup log in pastebin please

**Comment by tehrenderr** [comment]
Can you reply to my issue or what? I paid $15 for this plugin and the latest version doesn't even work. Try doing /od reload in game. About to chargeback if I don't get some support.

**Comment by miremo** [comment]
Sorry I have a little thing called school

**Comment by drtshock** [comment]
ok...

**Comment by miremo** [comment]
I will be putting the pastebin in 30 minutes and the start up is the.... Console?

**Comment by miremo** [comment]
http://pastebin.com/xdDbzcKS

**Comment by miremo** [comment]
....? Is it fixed

**Comment by drtshock** [comment]
Looks like it'll work fine to me.

**Comment by miremo** [comment]
Could you any chance have time to come online and see it

**Comment by miremo** [comment]
I guess I will test it out in another server to see if it is having conflict with another plugin

**Comment by WesGaming** [comment]
Dude use 4.3.10-SNAPSHOT it work for me but 4.4.11 doens't work for me. in 4.4.11 i have the same problem.

**Comment by WesGaming** [comment]
If you don't know how to download older versions link is here: https://www.spigotmc.org/resources/obsidiandestroyer.1625/history

**Comment by squidicuzz** [comment]
I am very sorry, I am busy with multiple things and have not had adequate time to focus on this.  I will have these issues fixed very soon, and a version that supports variant builds of spigot.
