### ISSUE TITLE
The plugin doesn't work fully

### ISSUE THREAD

**Issue by GoldyHD** [drtshock/ObsidianDestroyer#55]
So i drag and drop the plugin into my server and i reload and restart just to make sure. And then i go in game and i try to destroy obsidian (haven't changed config at this moment) and i cant use the potato and i cant break the obsidian 

Please can you help with this.

**Comment by drtshock** [comment]
can you please paste your server startup log in pastebin

**Comment by GoldyHD** [comment]
yes certainly:

http://pastebin.com/sr02sg60

**Comment by drtshock** [comment]
https://github.com/drtshock/ObsidianDestroyer/blob/master/obsidiandestroyer/src/main/resources/config.yml#L32

Try changing that. The plugin loaded fine.

**Comment by GoldyHD** [comment]
I have tried changing it to NETHER_STAR_ITEM but for some reason didnt work, And also NETHER_STAR and still didnt work

**Comment by drtshock** [comment]
Are you able to blow up obsidian with TNT? And can you give us you config.yml and materials.yml in a pastebin? I don't see any reason that the plugin wouldn't be working. It shows it loaded fine with no errors..

**Comment by GoldyHD** [comment]
Tnt does not blow up tent no and configure ang materials.yml I have not changed

**Comment by GoldyHD** [comment]
Do you know how to fix?

**Comment by GoldyHD** [comment]
Here is my issue:

https://youtu.be/vo4D17FB-1A

**Comment by WesGaming** [comment]
Dude use 4.3.10-SNAPSHOT it work for me but 4.4.11 doens't work for me. in 4.4.11 i have the same problem.

**Comment by WesGaming** [comment]
If you don't know how to download older versions link here: https://www.spigotmc.org/resources/obsidiandestroyer.1625/history

**Comment by squidicuzz** [comment]
Resolved.
