### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by Eternalrealms** [drtshock/ObsidianDestroyer#56]
The error looked different from the one I posted below so I thought I should post it again. 

Spigot 1.8.8 
Obsidian Destroyer 4.4.11-SNAPSHOT
Crash report: http://pastebin.com/Ng3c7nYJ

**Comment by squidicuzz** [comment]
Server crash from infinite `BlockIterator` issue should now be resolved with https://github.com/drtshock/ObsidianDestroyer/commit/c3e0f05a1da0da21b8383b12366c94132a1f0599

Please submit a new ticket if this occurs again.
