### ISSUE TITLE
Fixing obsidian not being broken

### ISSUE THREAD

**Issue by TylerrrV** [drtshock/ObsidianDestroyer#58]
I saw someone say this on spigot so I'm going to say it here to help others / help you fix it..

When changing OBSIDIAN to it's id (49) in the materials file, it allows breaking the obsidian and using the potato to check the durability.

I can confirm it worked, because after seeing that post and changing it, it worked for me. A $15 plugin with the main feature not working by default won't make people happy :P

**Comment by RingOfStorms** [comment]
This issue appears to be some sort of YAML issue, not an issue related directly to the plugin. The code supports names and OBSIDIAN is the proper material name. But if you fork it and try to debug the problem you'll see that the YAML parser seems to skip that section of the config for some reason. I don't know if this has to do with the default config and how it is generated, or maybe some update in YAML, but I'm confident it is not an issue with the code itself.

**Comment by LulzFTW** [comment]
It's because there are two entries for obsidian in the default materials.yml, the bottommost one being disabled. Removing the duplicate fixes the issue.
https://github.com/drtshock/ObsidianDestroyer/blob/1134cd5b3e12d3ec3b32e8cef1a6b7df4785dc2a/obsidiandestroyer/src/main/resources/materials.yml

GG

**Comment by squidicuzz** [comment]
Resolved in [caa77b111b44223ed0dbe73190d600145406d194](https://github.com/drtshock/ObsidianDestroyer/commit/caa77b111b44223ed0dbe73190d600145406d194) ...
