### ISSUE TITLE
Server Crash: is it cause by ObsidianDestroyer?

### ISSUE THREAD

**Issue by netherstar** [drtshock/ObsidianDestroyer#61]
today, my server crash 2 times,
first: http://paste.ubuntu.com/20779784/
seconds: http://paste.ubuntu.com/20779817/
is it cause by ObsidianDestroyer?
i Use:
- PaperSpigot 1.9.2
- ObsidiDestroyer build 218

**Comment by tuanjr** [comment]
new crash today: http://paste.ubuntu.com/21363830/

**Comment by drtshock** [comment]
@squidicuzz ;o

**Comment by tuanjr** [comment]
new crash today, pleaseeee fix it:
http://paste.ubuntu.com/21740125/

**Comment by tuanjr** [comment]
crash again, T_T please
http://paste.ubuntu.com/22020920/

**Comment by squidicuzz** [comment]
`Util.isTargetsPathBlocked()` issues... for some reason it checks infinite?
