### ISSUE TITLE
Plugin some times works

### ISSUE THREAD

**Issue by thomasb454** [drtshock/ObsidianDestroyer#7]
Hi,

Sometimes damage is done to Obsidian blocks [only block that I've tested on] and sometimes it doesn't.
No errors, nothing. Like I said; sometimes it works, sometimes it doesn't.

**Comment by thomasb454** [comment]
I understand I haven't given you much to go on, but any advances?

**Comment by squidicuzz** [comment]
I can not reproduce.  Perhaps there is another plugin interfering?

Is the faction offline at the time?

**Comment by thomasb454** [comment]
I'm pretty sure I've seen cases where the target faction is online and offline.

I'm not so sure about another plugin; possibly but I don't think I have any other plugins messing with this kind of thing.

**Comment by squidicuzz** [comment]
Try that latest version once it is available?

**Comment by thomasb454** [comment]
Will do.

**Comment by drtshock** [comment]
It's on spigot.

**Comment by thomasb454** [comment]
I don't have access to download from Spigot; this is why I asked for you to add me as a buyer on Skype.

**Comment by squidicuzz** [comment]
Any updates?

**Comment by thomasb454** [comment]
I completely forgot about this - the server is currently 1.8.3 and I believe I'm running the latest version. All is fine. 

Cheers.
