### ISSUE TITLE
Obsidian + Slab Glitch // Spawners

### ISSUE THREAD

**Issue by dotapurex1** [drtshock/ObsidianDestroyer#71]
Hello,

My players have discovered a bug with the plugin. When you place half slabs next to obsidian. The slab will not get blown up with TNT. Both the X and Y coordinates has to be negative. This only occurs when you are blowing the blocks from the west side. This is also happening with Mob Spawners.

Thanks!

**Comment by drtshock** [comment]
Which version of Obsidian Destroyer and spigot?

**Comment by dotapurex1** [comment]
I am using the Latest ObsidianDestroyer on Spigot 4.4.12 and paperspigot: https://puu.sh/zoC4g/3e509ecf8b.jpg

**Comment by dotapurex1** [comment]
Any updates on this? Thanks!

**Comment by squidicuzz** [comment]
Try version `4.4.15`

Please open new ticket is this still occurs..
