### ISSUE TITLE
Issue with PaperSpigot 1.7.10

### ISSUE THREAD

**Issue by EmperorPvP** [drtshock/ObsidianDestroyer#72]
I get this error when loading up the plugin: https://pastebin.com/01yRjUyq
The version im using is : https://yivesmirror.com/grab/paperspigot/PaperSpigot-1.7.10-R0.1-SNAPSHOT-latest.jar

**Comment by ArtelGG** [comment]
The plugin does not support 1.7.X.

**Comment by drtshock** [comment]
Spigot's blockexplode event change in may of 2015 broke that :\

**Comment by drtshock** [comment]
We check now if we should run this or not.
