### ISSUE TITLE
Set "End" in "Bedrock Border To Protect" and it won't work

### ISSUE THREAD

**Issue by IWetPro** [drtshock/ObsidianDestroyer#75]
I've set "End" in the "Bedrock Border to Protect" area of the config and it doesn't work, is it because that's the wrong world type name? Or because of a bug?

**Comment by drtshock** [comment]
Looks like it needs to be `THE_END` 
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/World.Environment.html
