### ISSUE TITLE
[1.12.2]Material warns

### ISSUE THREAD

**Issue by Biorn1950** [drtshock/ObsidianDestroyer#78]
Hello,

Some material warns:

`[WARN]: [ObsidianDestroyer] Non-Solid Material Type: Did not load 'PORTAL'
[WARN]: [ObsidianDestroyer] Non-Solid Material Type: Did not load 'ENDER_PORTAL'
[WARN]: [ObsidianDestroyer] Non-Solid Material Type: Did not load 'WATER'
[WARN]: [ObsidianDestroyer] Non-Solid Material Type: Did not load 'STATIONARY_WATER'
[WARN]: [ObsidianDestroyer] Non-Solid Material Type: Did not load 'LAVA'
[WARN]: [ObsidianDestroyer] Non-Solid Material Type: Did not load 'STATIONARY_LAVA'
[WARN]: [ObsidianDestroyer] Non-Solid Material Type: Did not load 'SKULL' `

**Comment by squidicuzz** [comment]
Materials issue due to version most likely.
Make sure the MATERIAL used in materials.yml matches to your minecraft server version.
