### ISSUE TITLE
BlockIterator Error.

### ISSUE THREAD

**Issue by Harry5573** [drtshock/ObsidianDestroyer#8]
Hey guys, getting this error http://pastebin.com/4DctTNwB. 

Plugin version: http://www.spigotmc.org/resources/obsidiandestroyer.1625/update?update=8618

**Comment by squidicuzz** [comment]
Okay thanks, I will find a fix to this.

**Comment by squidicuzz** [comment]
In the latest version, I have added some error trapping for if this occurs.  Please try it out once it is available.

**Comment by squidicuzz** [comment]
No reports of such since previous changes.
