### ISSUE TITLE
Obsidian Unbreakable In Faction Territory

### ISSUE THREAD

**Issue by ArmanA145** [drtshock/ObsidianDestroyer#9]
Obsidian does not take damage in faction territory but it does in wilderness, I am using FactionsUUID 1.6.9.5-U0.1.1.13-SNAPSHOT and ObsidianDestroyer 4.3.6

Spigot Version: http://prntscr.com/5oa1jr
Errors: None. Just obsidian gets durability taken down when blasted with TNT in wilderness, but not in claimed faction land.

**Comment by squidicuzz** [comment]
Is the faction "offline"?

**Comment by squidicuzz** [comment]
Could you also please post your config.yml and materials.yml file, I will load them on a test server to see.

**Comment by ArmanA145** [comment]
Config: http://pastebin.com/uq9yQmC0
Materials: http://pastebin.com/kHEVasZX

Happens in both cases, whether members are online or the faction is fully offline.

**Comment by squidicuzz** [comment]
Are explosions enabled for the faction, in Factions?

I have another version that you could perhaps try.  I will PM you on the spigot forums..

**Comment by squidicuzz** [comment]
Resolved in latest version
