### ISSUE TITLE
[Urgent] Plugin not working for any block other than Obsidian

### ISSUE THREAD

**Issue by Ferocimo** [drtshock/ObsidianDestroyer#90]
Hello,

We have another urgent issue : on our server we set the config up so obsidian can be destroyed after 200 hits, but End Stone Bricks is the new indestructible block.

This second feature is not working at all. End stone bricks can still be destroyed with TNT, as demonstrated below : 
https://streamable.com/iso1ac

We urgently need a fix for that issue because in the mean time, we litterally can't use your plugin.

Here is our config and material.yml : 
https://pastebin.com/U56DFhMU
https://pastebin.com/nz3X2m67

We also tried with that config for material.yml : 

>   END_STONE_BRICKS:

    BlastRadius: 0
    Destructible: false
    Enabled: true
    Durability:
      Amount: 99999
      Enabled: true
      FluidDamper: 0.0
      ChanceToDrop: 1
      ResetEnabled: true
      ResetAfter: 600000
    EnabledFor:
      TNT: false
      Creepers: false
      Ghasts: false
      Cannons: false
      Withers: false
      Minecarts: false

ObsidianDestroyer 4.4.17
Server Paper version git-Paper-235 (MC 1.15.2)

Thank you.

**Comment by Ferocimo** [comment]
@drtshock Did you have time to take a look at this ? Sorry to bump, it's relatively urgent...

**Comment by Ferocimo** [comment]
@drtshock As previously said this is urgent. Your plugin is currently not working properly and doesn't perform what we bought it for.

**Comment by squidicuzz** [comment]
You may add whatever materials you wish to the managed list..

**Comment by Ferocimo** [comment]
@squidicuzz Not only did you not answer an "urgent" querry for nearly TWO YEARS, you also managed to not read what the issue was : a material _**already added to the managed list**_ still being destructible. I think you win the award of the most unhelpful customer service of... 2020 I guess ?

Minecraft plugins in a nutshell.

**Comment by Momonche** [comment]
Some news about this ?

**Comment by Blamo27** [comment]
Oh my god, i subscribed to this issue two years ago… this plugin was completly broken too many issues. I had to create a new plugin myself in literaly 5 minutes 😅

**Comment by squidicuzz** [comment]
> @squidicuzz Not only did you not answer an "urgent" querry for nearly TWO YEARS, you also managed to not read what the issue was : a material _**already added to the managed list**_ still being destructible. I think you win the award of the most unhelpful customer service of... 2020 I guess ?
> 
> Minecraft plugins in a nutshell.

There is no issue.  Your `Blast Radius` is `0`  Try increasing this.
![image](https://user-images.githubusercontent.com/1578496/164104821-d8e32c30-058d-456e-a816-09c77d3da007.png)

**Comment by squidicuzz** [comment]
> Oh my god, i subscribed to this issue two years ago… this plugin was completly broken too many issues. I had to create a new plugin myself in literaly 5 minutes sweat_smile

Works fine here.  Glad you could make your own :+1:

**Comment by Ferocimo** [comment]
> > @squidicuzz Not only did you not answer an "urgent" querry for nearly TWO YEARS, you also managed to not read what the issue was : a material _**already added to the managed list**_ still being destructible. I think you win the award of the most unhelpful customer service of... 2020 I guess ?
> > Minecraft plugins in a nutshell.
> 
> There is no issue. Your `Blast Radius` is `0` Try increasing this. ![image](https://user-images.githubusercontent.com/1578496/164104821-d8e32c30-058d-456e-a816-09c77d3da007.png)

This is some piece of information that maybe I could have used two years ago.
